// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for android - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBDv92yD_zIYD7U5cyF-YUB10D2-YPbUGA',
    appId: '1:1007995331220:web:03db149d85161305e18a81',
    messagingSenderId: '1007995331220',
    projectId: 'weather-forecast-65d82',
    authDomain: 'weather-forecast-65d82.firebaseapp.com',
    storageBucket: 'weather-forecast-65d82.firebasestorage.app',
    measurementId: 'G-S0GDW0WMQ8',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC_6GoX9Lur_v5NSFF_7uWE4d6wgVUWQ3o',
    appId: '1:1007995331220:ios:2df770a755923d04e18a81',
    messagingSenderId: '1007995331220',
    projectId: 'weather-forecast-65d82',
    storageBucket: 'weather-forecast-65d82.firebasestorage.app',
    iosBundleId: 'com.example.gWeatherForecast',
  );
}
